ENUM_COLUMN_ID = 'Id'
ENUM_COLUMN_NAME = 'Name'

PARENT_CHECK_OUT = 0
TEACHER_CHECK_IN = 1
TEACHER_CHECK_OUT = 2
BREAKFAST_HOME = 3
LUNCH_HOME = 4
SNACKS_HOME = 5
BREAKFAST_SCHOOL = 6
LUNCH_SCHOOL = 7
SNACKS_SCHOOL = 8
NAP_TIME_MORNING = 9
NAP_TIME_AFTERNOON = 10
NAP_TIME_EVENING = 11
PLAY_OUTSIDE = 12
PLAY_INSIDE = 13
LEARN_ACTIVITY = 14
BOWEL_MOVEMENT = 15
WET_DIAPER = 16
DRY_DIAPER = 17
BEFORE_DROP_WAKEUP = 18
BEFORE_DROP_FOOD = 19
BEFORE_DROP_MOOD = 20
MOOD_AT_DAYCARE = 21


ENM_ACTIVITY_TYPE = Jenum.new('Activity Type')
ENM_ACTIVITY_TYPE.set_values([
  [PARENT_CHECK_OUT,'Parent Check-out'],
  [TEACHER_CHECK_IN,'Teacher Check-in'],
  [TEACHER_CHECK_OUT,'Teacher Check-out'],
  [BREAKFAST_HOME,'Breakfast Home'],
  [LUNCH_HOME,'Lunch Home'],
  [SNACKS_HOME,'Snacks Home'],
  [BREAKFAST_SCHOOL,'Breakfast School'],
  [LUNCH_SCHOOL,'Lunch School'],
  [SNACKS_SCHOOL,'Snacks School'],
  [NAP_TIME_MORNING,'Nap Time Morning'],
  [NAP_TIME_AFTERNOON,'Nap Time Afternoon'],
  [NAP_TIME_EVENING,'Nap Time Evening'],
  [PLAY_OUTSIDE,'Play Outside'],
  [PLAY_INSIDE,'Play Inside'],
  [LEARN_ACTIVITY,'Learn Activity'],
  [BOWEL_MOVEMENT,'Bowel Movement'],
  [WET_DIAPER,'Wet Diaper'],
  [DRY_DIAPER,'Dry Diaper'],
  [BEFORE_DROP_WAKEUP,'Before Drop Wakeup'],
  [BEFORE_DROP_FOOD,'Before Drop Food'],
  [BEFORE_DROP_MOOD,'Before Drop Mood'],
  [MOOD_AT_DAYCARE,'Mood At Daycare']
])

CLASSROOM_INFANT = 0
CLASSROOM_TODDLER = 1
CLASSROOM_DISCOVERY_PRE_SCHOOL = 2
CLASSROOM_PRE_SCHOOL = 3
CLASSROOM_PRE_KINDERGARTEN = 4

ENM_CLASSROOM_TYPE = Jenum.new('Classroom Type')
ENM_CLASSROOM_TYPE.set_values([[CLASSROOM_INFANT,'Infant'], [CLASSROOM_TODDLER,'Toddler'], [CLASSROOM_DISCOVERY_PRE_SCHOOL,'Discovery PreSchool'], [CLASSROOM_PRE_SCHOOL,'PreSchool'], [CLASSROOM_PRE_KINDERGARTEN,'PreKindergarten']])